# Generated by Django 4.2 on 2024-11-06 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('design_submissions', '0002_remove_userdesignsubmission_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdesignsubmission',
            name='status',
            field=models.CharField(choices=[('submitted', 'Submitted'), ('processing', 'Processing'), ('finalized', 'Finalized')], default='submitted', max_length=10),
        ),
    ]
