# Generated by Django 3.2.25 on 2024-10-31 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0006_orderreview'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderlineitem',
            name='size',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
