# Generated by Django 3.2.25 on 2024-11-01 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0007_orderlineitem_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderlineitem',
            name='size',
        ),
        migrations.AlterField(
            model_name='orderlineitem',
            name='product_size',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
