# Generated by Django 3.2.25 on 2024-11-01 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0010_alter_orderlineitem_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderlineitem',
            name='price_at_purchase',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
