# Generated by Django 4.2 on 2024-11-04 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name': 'Message', 'verbose_name_plural': 'Messages'},
        ),
    ]
