# Generated by Django 5.1.2 on 2024-10-15 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_remove_product_category_product_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='gender',
            field=models.CharField(blank=True, choices=[('men', 'Men'), ('women', 'Women')], max_length=10, null=True),
        ),
    ]
