# Generated by Django 5.1.2 on 2024-10-15 13:21

import markdownx.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=markdownx.models.MarkdownxField(),
        ),
    ]
