# Generated by Django 3.2.25 on 2024-10-29 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_category_is_main_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='is_main_category',
        ),
    ]
