# Generated by Django 3.2.25 on 2024-11-01 02:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_product_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='is_active',
        ),
    ]
