# Generated by Django 4.2 on 2024-11-05 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_product_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='updated_at',
        ),
    ]
